-- FLOOR는 집계 함수 x
SELECT 
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON c.CAR_TYPE = d.CAR_TYPE
    AND d.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND c.CAR_ID NOT IN (
        SELECT h.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.START_DATE <= '2022-11-30'
          AND h.END_DATE >= '2022-11-01'
  )
  AND FLOOR(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
