SELECT 
p.MEMBER_NAME,
r.REVIEW_TEXT,
DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE p
JOIN REST_REVIEW r
ON p.MEMBER_ID = r.MEMBER_ID
WHERE  
p.MEMBER_ID =
(
    SELECT r.MEMBER_ID
    FROM REST_REVIEW r
    -- ORDER BY에서 집계 함수 사용 시 반드시 GROUP BY 써야 함
    GROUP BY r.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY 
r.REVIEW_DATE,
r.REVIEW_TEXT;
