
SELECT 
ID,
-- NTILE(수) OVER (ORDER BY(조건) DESC)
CASE NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) 
-- WHEN 숫자 THEN
WHEN 1 THEN 'CRITICAL' 
WHEN 2 THEN 'HIGH'
WHEN 3 THEN 'MEDIUM'
WHEN 4 THEN 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;
