
SELECT 
c.ID, 
c.GENOTYPE, 
p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA p
 JOIN ECOLI_DATA c
ON c.PARENT_ID = p.ID
-- c.GENOTYPE & p.GENOTYPE = p.GENOTYPE 부모 & 자식(비트 연산) = 부모
WHERE (c.GENOTYPE & p.GENOTYPE) = p.GENOTYPE
ORDER BY c.ID;
