-- UNION ALL
SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) j
ON f.FLAVOR = j.FLAVOR
GROUP BY f.FLAVOR
ORDER BY SUM(f.TOTAL_ORDER + j.JULY_TOTAL) DESC
LIMIT 3;

# SELECT FLAVOR
# FROM (
#     SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
#     UNION ALL
#     SELECT FLAVOR, TOTAL_ORDER FROM JULY
# ) t # 별칭 필수
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3;
